name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt

      - name: Run application test
        run: |
          echo "Hello world test passed!"  # Replace with real tests

  code-quality:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flake8
        run: pip install flake8

      - name: Run Flake8
        run: flake8 app

  docker-build:
    runs-on: ubuntu-latest
    needs: code-quality

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install Docker
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_TOKEN}}

      - name: Docker Push
        uses: docker/build-push-action@v6
        with:
          context: app/
          file: Dockerfile
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/flaskapp:${{github.run_id}}

  update-k8s:
    runs-on: ubuntu-latest  
    needs: docker-build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
            token: ${{secrets.GIT_TOKEN}}         

      - name: Update Kubernetes manifest
        run: |
          sed -i "s|image:.*|image: ${{secrets.DOCKER_USERNAME}}/flaskapp:${{github.run_id}}|" k8s/deployment.yaml
          cat k8s/deployment.yaml
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "[skip ci] Update deployment image to $IMAGE_NAME:${{github.run_id}}"
          file_pattern: 'k8s/deployment.yaml'
          run: git push
          token: ${{secrets.GIT_TOKEN}}
        
    

