name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run application test
        run: |
          echo "Hello world test passed!"  # Replace with real tests

  code-quality:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flake8
        run: pip install flake8

      - name: Run Flake8
        run: flake8 app

  docker-build:
    runs-on: ubuntu-latest
    needs: code-quality

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image tag
        id: vars
        run: echo "tag=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        run: |
          docker build -t $IMAGE_NAME:${{ steps.vars.outputs.tag }} .
          docker push $IMAGE_NAME:${{ steps.vars.outputs.tag }}

      - name: Update Kubernetes manifest
        run: |
          sed -i "s|image:.*|image: $IMAGE_NAME:${{ steps.vars.outputs.tag }}|" k8s/deployment.yaml
          cat k8s/deployment.yaml

      - name: Commit manifest changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update manifest with image ${{ steps.vars.outputs.tag }}"
          file_pattern: 'k8s/deployment.yaml'
